// Generated by https://quicktype.io

export interface IDeposit {
    created_at: string;
    updated_at: string;
    id: number;
    user_id: number;
    amount: number;
    deposit_account_id: number;
    is_reviewed: boolean;
    is_virtual_deposit: boolean;
    comments: string;
    remark: string;
}
