// Generated by https://quicktype.io

export interface IMember {
    id: number;
    username: string;
    is_real: boolean;
    is_verified: boolean;
    real_name: null;
    id_number_cccd: string;
    id_front_cccd: string;
    id_back_cccd: string;
    phone: string;
    bank_name: string;
    bank_number: string;
    bank_branch: string;
    account_name: string;
    withdraw_tips: string;
    balance: string;
    balance_frozen: string;
    balance_avail: string;
    balance_avail_newshare: string;
    total_assets: string;
    withdraw_avail: string;
    profit: string;
    sell_amount_day: null;
    hold_value: number;
    online_service: string;
    agent_code: string;
    superior: string | null;
    last_login_ip: string;
    is_playing_board: boolean;
    ipo_application: boolean;
    created_by: string;
    created_at: null;
    __entity: string;
}
