// Generated by https://quicktype.io

import { IDeposit } from './deposit'
import { IMember } from './member'
import { IPosition } from './position'
import { IWithdrawal } from './withdrawals'

export interface ITransaction {
    created_at: string;
    updated_at: string;
    id: number;
    type: number;
    before: number;
    after: number;
    app_user: IMember;
    withdrawal: IWithdrawal | null;
    deposit: IDeposit | null;
    position: IPosition | null;
}

export enum TRANSACTION_TYPES {
  BUY,
  SELL,
  WITHDRAW,
  DEPOSIT,
}

export interface IOrder {
  created_at: string;
  id: number;
  type: string;
  quantity: number;
  stock_code: string;
  amount: number;
  user_id: number;
  is_resolved: boolean;
  remarks: string;
  stock_market: string;
  stock_name: string;
  zhangting: number;
  dieting: number;
  trading_session: string;
  price: number;
  fee_rate: number;
  actual_amount: number;
  username: string;
  updated_at: string;
  real_name: string;
  agent: string;
  superior: string;
}
