// Generated by https://quicktype.io

import { IDeposit } from './deposit'
import { IMember } from './member'
import { IPosition } from './position'
import { IWithdrawal } from './withdrawals'

export interface ITransaction {
    created_at: string;
    updated_at: string;
    id: number;
    type: number;
    before: number;
    after: number;
    app_user: IMember;
    withdrawal: IWithdrawal | null;
    deposit: IDeposit | null;
    position: IPosition | null;
}

export enum TRANSACTION_TYPES {
  BUY,
  SELL,
  WITHDRAW,
  DEPOSIT,
}
